[package]
name = "df-rs-ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
df-rs = { path = "..", version = "*" }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
simple_logger = "5.0.0"
libc = "0.2.169"

[lib]
crate-type = ["cdylib"]
